### ISSUE TITLE
run example fail

### ISSUE THREAD

**Issue by GreedyPirate** [openzipkin/zipkin-php-example#9]
hi, i am using this example , followed your guide, when i input curl http://localhost:8081 in terminal, i got this error blow
```
<br />
<b>Fatal error</b>:  Uncaught TypeError: Argument 2 passed to Zipkin\Reporters\Http::__construct() must be of the type array, object given, called in /Users/admin/private/zipkin-php-example/functions.php on line 18 and defined in /Users/admin/private/zipkin-php-example/vendor/jcchavezs/zipkin/src/Zipkin/Reporters/Http.php:29
Stack trace:
#0 /Users/admin/private/zipkin-php-example/functions.php(18): Zipkin\Reporters\Http-&gt;__construct(Object(Zipkin\Reporters\Http\CurlFactory), Object(Monolog\Logger))
#1 /Users/admin/private/zipkin-php-example/frontend.php(11): create_tracing('frontend', '127.0.0.1')
#2 {main}
  thrown in <b>/Users/admin/private/zipkin-php-example/vendor/jcchavezs/zipkin/src/Zipkin/Reporters/Http.php</b> on line <b>29</b><br />
```
i am a java programer，try to build tracing system between java and php， need some help @jcchavezs

**Comment by jcchavezs** [comment]
Thanks for coming up with this issue!

I will look into it in a couple of hours. You can also reach for help at
gitter.im/jcchavezs or gitter.in/openzipkin

> --

*José Carlos*
